---
title: Ocean Blue Living
url: http://oceanblueliving.siteleaf.net
timezone: Australia/Brisbane
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  home:
    title: home
    output: false
    headline: We’re craftspeople who love transforming spaces.
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
exclude:
- node_modules
