---
title: Ocean Blue Living
timezone: Australia/Brisbane
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  home:
    title: home
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:slug/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
exclude:
- node_modules
- README.markdown
- package.json
- gulp.js
- gulpfile.js
contact-phone: '0409 726 128 '
contact-email: info@oceanblueliving.com.au
contact-address: |-
  3/169 Newell Street, Cairns
  Queensland 4870 Australia
contact-open: Open Tues–Thurs 9am–2pm
contact-appt: Other times by appointment
social-facebook: https://www.facebook.com/oceanblueliving
social-pinterest: https://www.facebook.com/oceanblueliving
