---
title: OceanBlue Living
timezone: Australia/Brisbane
collections:
  home:
    title: Home
    output: false
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:slug/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
gems:
- jekyll-seo-tag
exclude:
- node_modules
- README.markdown
- package.json
- gulp.js
- gulpfile.js
url: http://oceanblueliving.com.au
logo: http://oceanblueliving.com.au/uploads/logo.png
feed_url: "/feed.xml"
sitemap_url: "/map.xml"
description: 'We’re metalworks craftspeople who love transforming living spaces. We
  make elegant, functional, and timeless architectural applications that are weatherproof
  and durable both indoors and outdoors. From screens, panels, gates and letterboxes,
  to signage, wall art and outdoor garden sculpture, we bring your ideas to life.
  Designed and built in our Cairns workshop, Queensland, Australia.

'
keywords: 'decorative screens, security screens, laser cut screens, panels, gates,
  letterboxes, fire pits, signage, wall art, garden art, outdoor sculpture, custom
  made metalworks, Cairns, Queensland, Australia

'
author: OceanBlue Living + patternworks.com.au
google-analytics: UA-81874944-1
contact-phone: '0409 726 128 '
contact-email: info@oceanblueliving.com.au
contact-address: |
  116 Lyons Street, Cairns
  Queensland 4870 Australia
contact-open: Open Mon-Fri 9am–3.30pm
contact-appt: Other times by appointment
social-facebook: https://www.facebook.com/oceanblueliving
social-instagram: https://www.instagram.com/oceanblueliving
social-pinterest: https://au.pinterest.com/oceanblueliving
